name: synrg
description: A Very Good Project created by Very Good CLI.
version: 0.5.4
homepage: https://www.synrg.software/
repository: https://github.com/santiagoBaro/synrg_pkg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.15.5
  cloud_functions: ^4.6.6
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  firebase_analytics: ^10.8.7
  firebase_auth: ^4.17.4
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.16
  firebase_database: ^10.4.7
  firebase_performance: ^0.9.3+15
  firebase_remote_config: ^4.3.15
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gen: ^5.4.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.3
  intl: ^0.19.0
  meta: ^1.12.0
  quickalert: ^1.0.2
  shared_preferences: ^2.2.3
  toastification: ^2.0.0
  uuid: ^4.3.3

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.0.0
  extra_pedantic: 3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
