name: synrg
description: A Very Good Project created by Very Good CLI.
version: 0.2.1
homepage: https://www.synrg.software/
repository: https://github.com/santiagoBaro/synrg_pkg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.15.5
  cloud_functions: ^4.6.6
  firebase_analytics: ^10.8.7
  firebase_auth: ^4.17.4
  firebase_crashlytics: ^3.4.16
  firebase_database: ^10.4.7
  firebase_performance: ^0.9.3+15
  firebase_remote_config: ^4.3.15
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  intl: ^0.19.0
  meta: ^1.10.0
  quickalert: ^1.0.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
