name: synrg
description: A Very Good Project created by Very Good CLI.
version: 0.6.3
homepage: https://www.synrg.software/
repository: https://github.com/santiagoBaro/synrg_pkg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.7.6
  collection: ^1.19.1
  device_info_plus: ^10.1.2
  equatable: ^2.0.7
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_database: ^10.5.7
  firebase_performance: ^0.9.4+7
  firebase_remote_config: ^4.4.7
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.8.0
  go_router: ^14.7.2
  intl: ^0.20.2
  meta: ^1.15.0
  quickalert: ^1.1.0
  shared_preferences: ^2.5.1
  toastification: ^2.3.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  extra_pedantic: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
