name: synrg
description: >
  A complete Flutter toolkit for Firebase integration, typed data modeling, modular architecture, 
  UI feedback, and scalable app development using BLoC.
version: 1.1.0
homepage: https://www.synrg.software/
repository: https://github.com/santiagoBaro/synrg_pkg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1
  collection: ^1.19.1
  device_info_plus: ^11.4.0
  equatable: ^2.0.7
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_database: ^11.3.6
  firebase_performance: ^0.10.1+6
  firebase_remote_config: ^5.4.4
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.8.0
  go_router: ^15.1.2
  google_sign_in: ^6.3.0
  http: ^1.4.0
  image: ^4.5.4
  intl: ^0.20.2
  meta: ^1.15.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  quickalert: ^1.1.0
  shared_preferences: ^2.5.1
  sign_in_with_apple: ^7.0.1
  toastification: ^3.0.2
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  extra_pedantic: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
