name: synrg
description: A Very Good Project created by Very Good CLI.
version: 0.1.2
homepage: https://www.synrg.software/
repository: https://github.com/santiagoBaro/synrg_pkg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  intl: ^0.19.0
  meta: ^1.10.0
  quickalert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
